import fs from "node:fs";
import path from "node:path";
import type { OpenColabConfig } from "./config.js";
import type { Db } from "./db.js";
import { ensurePaperLayout } from "./paths.js";
import { newId, nowIso } from "./utils.js";

export class PaperService {
  constructor(
    private readonly db: Db,
    private readonly config: OpenColabConfig
  ) {}

  ensureRunDraft(projectName: string, runId: string, title: string): { paperId: string; latexMainPath: string } {
    const row = this.db.get<{ paper_id: string; latex_main_path: string }>(
      `SELECT paper_id, latex_main_path
       FROM paper_drafts
       WHERE project_name = :project_name AND run_id = :run_id`,
      {
        project_name: projectName,
        run_id: runId
      }
    );

    if (row) {
      return {
        paperId: row.paper_id,
        latexMainPath: row.latex_main_path
      };
    }

    const paperId = newId("paper");
    const { latexDir } = ensurePaperLayout(this.config, projectName, paperId);
    const latexMainPath = path.join(latexDir, "main.tex");
    fs.writeFileSync(latexMainPath, initialLatex(title), "utf8");
    const now = nowIso();

    this.db.run(
      `INSERT INTO paper_drafts (paper_id, project_name, run_id, title, latex_main_path, updated_at, created_at)
       VALUES (:paper_id, :project_name, :run_id, :title, :latex_main_path, :updated_at, :created_at)`,
      {
        paper_id: paperId,
        project_name: projectName,
        run_id: runId,
        title,
        latex_main_path: latexMainPath,
        updated_at: now,
        created_at: now
      }
    );

    return { paperId, latexMainPath };
  }

  appendSection(paperId: string, sectionTitle: string, body: string): void {
    const row = this.db.get<{ latex_main_path: string }>(
      `SELECT latex_main_path FROM paper_drafts WHERE paper_id = :paper_id`,
      { paper_id: paperId }
    );

    if (!row) {
      throw new Error(`Paper not found: ${paperId}`);
    }

    const insertion = `\n\\section{${escapeLatex(sectionTitle)}}\n${escapeLatex(body)}\n`;
    fs.appendFileSync(row.latex_main_path, insertion, "utf8");

    this.db.run(
      `UPDATE paper_drafts
       SET updated_at = :updated_at
       WHERE paper_id = :paper_id`,
      {
        paper_id: paperId,
        updated_at: nowIso()
      }
    );
  }
}

function initialLatex(title: string): string {
  const safeTitle = escapeLatex(title);
  return `\\documentclass{article}\n\\usepackage[utf8]{inputenc}\n\\title{${safeTitle}}\n\\author{OpenColab Research Team}\n\\date{\\today}\n\\begin{document}\n\\maketitle\n\\begin{abstract}\nDraft generated by OpenColab.\n\\end{abstract}\n\\section{Introduction}\nTODO.\n\\end{document}\n`;
}

function escapeLatex(input: string): string {
  return input
    .replace(/\\/g, "\\\\textbackslash{}")
    .replace(/&/g, "\\\\&")
    .replace(/%/g, "\\\\%")
    .replace(/\$/g, "\\\\$")
    .replace(/#/g, "\\\\#")
    .replace(/_/g, "\\\\_")
    .replace(/{/g, "\\\\{")
    .replace(/}/g, "\\\\}");
}
